const KEY='inventory-system-v1', SESSION='inventory-session-v1'
const seed={users:[['admin','Alice Admin','admin@example.com','admin','admin123'],['employee','Eli Employee','employee@example.com','employee','employee123'],['user','Uma User','user@example.com','user','user123']],categories:[['Stationery','Office and paper supplies'],['Electronics','Devices, cables and accessories'],['Cleaning','Janitorial consumables']],products:[['SKU-1001','A4 Paper Ream','Stationery',120,20,6.5,'A1-01'],['SKU-1002','Ballpoint Pen (Box of 50)','Stationery',18,20,12,'A1-02'],['SKU-1003','Notebook A5','Stationery',80,15,3.25,'A1-03'],['SKU-1004','Highlighter Set','Stationery',50,10,5.75,'A1-04'],['SKU-2001','USB-C Cable 2m','Electronics',45,10,8.75,'B2-04'],['SKU-2002','Wireless Mouse','Electronics',7,8,21.99,'B2-05'],['SKU-2003','HDMI Cable 1m','Electronics',35,10,6.5,'B2-01'],['SKU-2004','Webcam HD','Electronics',12,5,45,'B2-02'],['SKU-3001','Disinfectant 5L','Cleaning',30,6,15.4,'C3-01'],['SKU-3002','Microfibre Cloth','Cleaning',4,10,2.25,'C3-02'],['SKU-3003','Paper Towels','Cleaning',60,15,4.5,'C3-03'],['SKU-3004','Hand Sanitizer 500ml','Cleaning',25,8,3.99,'C3-04']]}
const icons={'SKU-1001':'a4-paper-ream.svg','SKU-1002':'ballpoint-pen-box-of-50.svg','SKU-1003':'notebook-a5.svg','SKU-1004':'highlighter-set.svg','SKU-2001':'usb-c-cable-2m.svg','SKU-2002':'wireless-mouse.svg','SKU-2003':'hdmi-cable-1m.svg','SKU-2004':'webcam-hd.svg','SKU-3001':'disinfectant-5l.svg','SKU-3002':'microfibre-cloth.svg','SKU-3003':'paper-towels.svg','SKU-3004':'hand-sanitizer-500ml.svg'}
const digest=p=>{let h1=0x811c9dc5,h2=0x01000193;for(let i=0;i<p.length;i++){h1=Math.imul(h1^p.charCodeAt(i),16777619)>>>0;h2=Math.imul(h2+p.charCodeAt(i)*(i+1),2246822519)>>>0}return h1.toString(16).padStart(8,'0')+h2.toString(16).padStart(8,'0')}
let db
function persist(){localStorage.setItem(KEY,JSON.stringify(db))}
function next(c){db.nextId[c]=(db.nextId[c]||0)+1;return db.nextId[c]}
function seedDb(){db={nextId:{},users:[],categories:[],products:[],movements:[],requests:[]};seed.users.forEach(r=>db.users.push({id:next('users'),username:r[0],fullName:r[1],email:r[2],role:r[3],passwordHash:digest(r[4]),isActive:true,createdAt:new Date().toISOString()}));seed.categories.forEach(r=>db.categories.push({id:next('categories'),name:r[0],description:r[1]}));const admin=db.users[0];seed.products.forEach(r=>{const c=db.categories.find(x=>x.name===r[2]);const p={id:next('products'),sku:r[0],name:r[1],categoryId:c?.id??null,quantity:r[3],reorderLevel:r[4],unitPrice:r[5],location:r[6],description:`${r[1]} held in ${r[6]}.`,imageUrl:'',createdAt:new Date().toISOString()};db.products.push(p);db.movements.push({id:next('movements'),productId:p.id,userId:admin.id,type:'in',quantity:p.quantity,note:'Opening stock',createdAt:new Date().toISOString()})});persist()}
export function load(){try{db=JSON.parse(localStorage.getItem(KEY)||'null')}catch{}if(!db)seedDb();return db}
load()
export const byId=(c,id)=>db[c].find(x=>x.id===Number(id))
export const categories=()=>db.categories.slice().sort((a,b)=>a.name.localeCompare(b.name))
export const products=()=>db.products.slice().sort((a,b)=>a.name.localeCompare(b.name))
export const users=()=>db.users.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt))
export const requests=(filter={})=>db.requests.filter(r=>(!filter.status||r.status===filter.status)&&(!filter.requesterId||r.requesterId===filter.requesterId)).slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt))
export const movements=(limit=999,userId)=>db.movements.filter(m=>userId===undefined||m.userId===userId).slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,limit)
export const categoryName=p=>byId('categories',p.categoryId)?.name||'uncategorised'
export const isLowStock=p=>p.quantity<=p.reorderLevel
export const stockValue=p=>p.quantity*p.unitPrice
export const productIcon=p=>icons[p.sku]?`/product-icons/${icons[p.sku]}`:null
export const metrics=()=>{const ps=db.products,low=ps.filter(isLowStock);return{productCount:ps.length,totalUnits:ps.reduce((s,p)=>s+p.quantity,0),stockValue:ps.reduce((s,p)=>s+stockValue(p),0),lowStock:low,lowStockCount:low.length,pendingRequests:db.requests.filter(r=>r.status==='pending').length,userCount:db.users.length}}
export const currentUser=()=>{const u=byId('users',localStorage.getItem(SESSION));return u?.isActive?u:null}
export const login=(username,password)=>{const u=db.users.find(x=>x.username.toLowerCase()===String(username).toLowerCase());if(!u||u.passwordHash!==digest(password))return{error:'Invalid username or password.'};if(!u.isActive)return{error:'This account has been deactivated.'};localStorage.setItem(SESSION,String(u.id));return{user:u}}
export const logout=()=>localStorage.removeItem(SESSION)
export const register=(fullName,username,email,password)=>{if(db.users.some(u=>u.username.toLowerCase()===username.toLowerCase()||u.email.toLowerCase()===email.toLowerCase()))return{error:'Username or email is already registered.'};const u={id:next('users'),username,fullName,email,role:'user',passwordHash:digest(password),isActive:true,createdAt:new Date().toISOString()};db.users.push(u);persist();localStorage.setItem(SESSION,String(u.id));return{user:u}}
export const createProduct=(data,actor)=>{if(db.products.some(p=>p.sku===data.sku))return{error:`SKU ${data.sku} already exists.`};const p={id:next('products'),sku:data.sku,name:data.name,description:data.description||'',categoryId:data.categoryId?Number(data.categoryId):null,quantity:Number(data.quantity)||0,reorderLevel:Number(data.reorderLevel)||0,unitPrice:Number(data.unitPrice)||0,location:data.location||'',imageUrl:data.imageUrl||'',createdAt:new Date().toISOString()};db.products.push(p);if(p.quantity)db.movements.push({id:next('movements'),productId:p.id,userId:actor?.id,type:'in',quantity:p.quantity,note:'Opening stock',createdAt:new Date().toISOString()});persist();return{product:p}}
export const updateProduct=(id,data)=>{const p=byId('products',id);if(!p)return{error:'Product not found.'};Object.assign(p,{name:data.name,description:data.description||'',categoryId:data.categoryId?Number(data.categoryId):null,reorderLevel:Number(data.reorderLevel)||0,unitPrice:Number(data.unitPrice)||0,location:data.location||''});persist();return{product:p}}
export const deleteProduct=id=>{const n=Number(id);db.products=db.products.filter(p=>p.id!==n);db.movements=db.movements.filter(m=>m.productId!==n);db.requests=db.requests.filter(r=>r.productId!==n);persist()}
export const applyMovement=(productId,type,quantity,actor,note='')=>{const p=byId('products',productId),q=Number(quantity);if(!p)return{error:'Product not found.'};if(!Number.isFinite(q)||q<0||(type!=='adjust'&&q<=0))return{error:'Quantity must be greater than zero.'};if(type==='in')p.quantity+=q;else if(type==='out'){if(q>p.quantity)return{error:`Cannot remove ${q} units; only ${p.quantity} in stock.`};p.quantity-=q}else p.quantity=q;db.movements.push({id:next('movements'),productId:p.id,userId:actor?.id||null,type,quantity:q,note,createdAt:new Date().toISOString()});persist();return{product:p}}
export const createCategory=(name,description)=>{if(db.categories.some(c=>c.name.toLowerCase()===name.toLowerCase()))return{error:'Category already exists.'};const c={id:next('categories'),name,description:description||''};db.categories.push(c);persist();return{category:c}}
export const createUser=data=>{if(db.users.some(u=>u.username.toLowerCase()===data.username.toLowerCase()||u.email.toLowerCase()===data.email.toLowerCase()))return{error:'Username or email already in use.'};const u={id:next('users'),username:data.username,fullName:data.fullName,email:data.email,role:data.role,passwordHash:digest(data.password),isActive:true,createdAt:new Date().toISOString()};db.users.push(u);persist();return{user:u}}
export const setRole=(id,role,actor)=>{const u=byId('users',id);if(!u)return{error:'User not found.'};if(u.id===actor.id)return{error:'You cannot change your own role.'};u.role=role;persist();return{user:u}}
export const toggleUser=(id,actor)=>{const u=byId('users',id);if(!u)return{error:'User not found.'};if(u.id===actor.id)return{error:'You cannot deactivate your own account.'};u.isActive=!u.isActive;persist();return{user:u}}
export const updateProfile=(user,data)=>{if(data.username.toLowerCase()!==user.username.toLowerCase()&&db.users.some(u=>u.id!==user.id&&u.username.toLowerCase()===data.username.toLowerCase()))return{error:'Username is already taken.'};if(data.newPassword&&digest(data.currentPassword||'')!==user.passwordHash)return{error:'Current password is incorrect.'};Object.assign(user,{username:data.username,fullName:data.fullName,email:data.email});if(data.newPassword)user.passwordHash=digest(data.newPassword);persist();return{user}}
export const createRequest=(productId,quantity,reason,actor)=>{const p=byId('products',productId),q=Number(quantity);if(!p)return{error:'Product not found.'};if(!q||q<=0)return{error:'Quantity must be greater than zero.'};const r={id:next('requests'),productId:p.id,requesterId:actor.id,handledById:null,quantity:q,reason:reason||'',status:'pending',createdAt:new Date().toISOString()};db.requests.push(r);persist();return{request:r}}
export const handleRequest=(id,action,actor)=>{const r=byId('requests',id);if(!r)return{error:'Request not found.'};if(action==='approve'||action==='reject')r.status=action==='approve'?'approved':'rejected';else if(action==='fulfill'){const out=applyMovement(r.productId,'out',r.quantity,actor,`Fulfilled request #${r.id}`);if(out.error)return out;r.status='fulfilled'}else return{error:'Unknown action.'};r.handledById=actor.id;persist();return{request:r}}
export const cancelRequest=(id,actor)=>{const r=byId('requests',id);if(!r||r.requesterId!==actor.id)return{error:'Request not found.'};if(r.status!=='pending')return{error:'Only pending requests can be cancelled.'};db.requests=db.requests.filter(x=>x.id!==r.id);persist();return{ok:true}}
export const reset=()=>{localStorage.removeItem(KEY);localStorage.removeItem(SESSION);seedDb()}
